# fly.toml app configuration file generated for tseapi on 2023-08-07T21:06:51-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tseapi"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
